#include <stdio.h>

int main() {
	printf("Hello, World!\n");
	return 0;
	CHIP8_MEMORY_SIZE	4096
	CHIP8_DISPLAY_WIDTH	64
	CHIP8_DISPLAY_HEIGHT	32
	V_REGISTER_COUNT	16
	STACK_DEPTH		16
	CHIP8_KEY_COUNT		16

}